[build]
  # Directory to change to before starting a build
  base = "landing/"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "landing/"
  
  # Default build command
  command = "echo 'Static site - no build required'"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Redirect rules for SPA routing (if needed)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Redirect for old URLs (if any)
[[redirects]]
  from = "/ai-calendar-landing.html"
  to = "/index.html"
  status = 301

# Force HTTPS redirect
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"
    
    # CORS headers (if needed for API calls)
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Specific headers for HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "text/html; charset=utf-8"

# Headers for static assets
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/png"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/jpeg"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/svg+xml"

# Headers for fonts
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "font/woff2"

[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "font/woff"

# Headers for JSON files
[[headers]]
  for = "*.json"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "application/json"

# Function configuration (if needed for serverless functions)
[functions]
  directory = "netlify/functions"

# Edge functions (if needed)
[edge_functions]
  directory = "netlify/edge-functions"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-sitemap"
  
  [plugins.inputs]
    buildDir = "landing/"
    exclude = ["/404.html", "/admin/*"]

# Form handling (if needed)
[forms]
  # Enable form detection
  enable_forms = true

# Dev configuration
[dev]
  # Port for local development
  port = 8888
  
  # Command to run local development server
  command = "python -m http.server 8888"
  
  # Target port for proxying
  target_port = 8888
  
  # Framework detection
  framework = "#static"
