[build]
  publish = "."
  command = "echo 'Static site - no build required'"

# Redirect for old URLs
[[redirects]]
  from = "/ai-calendar-landing.html"
  to = "/index.html"
  status = 301

# Force HTTPS redirect
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true